import { PricingRate, IntercityRoute, SiteSettings, PromotionBanner, CityLandmark } from './types';

export const TURBAT_LANDMARKS: CityLandmark[] = [
  { id: 'lm-1', name: 'City Thana, Thana Road', nameUrdu: 'سٹی تھانہ، تھانہ روڈ', name_urdu: 'سٹی تھانہ، تھانہ روڈ', area: 'Central Turbat', lat: 26.0031, lng: 63.0544, is_active: true },
  { id: 'lm-2', name: 'Turbat International Airport', nameUrdu: 'تربت انٹرنیشنل ایئرپورٹ', name_urdu: 'تربت انٹرنیشنل ایئرپورٹ', area: 'Airport Road', lat: 25.9863, lng: 63.0312, is_active: true },
  { id: 'lm-3', name: 'University of Turbat (UoT)', nameUrdu: 'یونیورسٹی آف تربت', name_urdu: 'یونیورسٹی آف تربت', area: 'M-8 Ginna', lat: 26.0289, lng: 63.0978, is_active: true },
  { id: 'lm-4', name: 'Main Bazaar / Shahi Bazaar', nameUrdu: 'مین بازار / شاہی بازار', name_urdu: 'مین بازار / شاہی بازار', area: 'Central Turbat', lat: 26.0055, lng: 63.0501, is_active: true },
  { id: 'lm-5', name: 'District Headquarters (DHQ) Hospital', nameUrdu: 'ڈی ایچ کیو ہسپتال تربت', name_urdu: 'ڈی ایچ کیو ہسپتال تربت', area: 'Hospital Road', lat: 26.0082, lng: 63.0485, is_active: true },
  { id: 'lm-6', name: 'Absar Chowk', nameUrdu: 'ابسر چوک', name_urdu: 'ابسر چوک', area: 'Absar', lat: 25.9924, lng: 63.0721, is_active: true },
  { id: 'lm-7', name: 'Malikabad / Aabsar Road', nameUrdu: 'ملک آباد / ابسر روڈ', name_urdu: 'ملک آباد / ابسر روڈ', area: 'Malikabad', lat: 26.0125, lng: 63.0655, is_active: true },
  { id: 'lm-8', name: 'D-Baloch Chowk', nameUrdu: 'ڈی بلوچ چوک', name_urdu: 'ڈی بلوچ چوک', area: 'D-Baloch', lat: 26.0188, lng: 63.0412, is_active: true },
  { id: 'lm-9', name: 'Singanisar Chowk', nameUrdu: 'سنگانی سر چوک', name_urdu: 'سنگانی سر چوک', area: 'Singanisar', lat: 25.9875, lng: 63.0611, is_active: true },
  { id: 'lm-10', name: 'Ginna Road / M-8 CPEC Junction', nameUrdu: 'گنہ روڈ / ایم 8 جنکشن', name_urdu: 'گنہ روڈ / ایم 8 جنکشن', area: 'Ginna', lat: 26.0351, lng: 63.1120, is_active: true },
  { id: 'lm-11', name: 'Circuit House Turbat', nameUrdu: 'سرکٹ ہاؤس تربت', name_urdu: 'سرکٹ ہاؤس تربت', area: 'Officers Colony', lat: 26.0101, lng: 63.0588, is_active: true },
  { id: 'lm-12', name: 'Turbat Public School & College', nameUrdu: 'تربت پبلک اسکول و کالج', name_urdu: 'تربت پبلک اسکول و کالج', area: 'Absar Road', lat: 25.9981, lng: 63.0699, is_active: true },
  { id: 'lm-13', name: 'Kech River View Point', nameUrdu: 'کیچ ریور ویو پوائنٹ', name_urdu: 'کیچ ریور ویو پوائنٹ', area: 'Kech River', lat: 26.0150, lng: 63.0380, is_active: true },
  { id: 'lm-14', name: 'Government Degree College Turbat', nameUrdu: 'گورنمنٹ ڈگری کالج تربت', name_urdu: 'گورنمنٹ ڈگری کالج تربت', area: 'College Road', lat: 26.0012, lng: 63.0531, is_active: true },
];

export const INITIAL_LANDMARKS = TURBAT_LANDMARKS;

export const INITIAL_PRICING_RATES: PricingRate[] = [
  {
    id: 'olak-bike',
    service_name: 'OLAK Bike',
    service_name_urdu: 'اولاک بائیک',
    service_type: 'bike',
    vehicle_models: 'Motorcycle (70cc / 125cc)',
    base_fare: 50,
    per_km_charge: 25,
    waiting_charge_per_min: 5,
    minimum_fare: 80,
    cancellation_fee: 50,
    operating_hours: '6:00 AM – 12:00 AM',
    service_areas: 'Turbat City Limits & Suburbs',
    is_active: true,
    icon_name: 'Bike',
    tagline: 'Fastest & Most Affordable',
    capacity: '1 Rider',
  },
  {
    id: 'olak-rickshaw',
    service_name: 'OLAK Rickshaw / Bolan',
    service_name_urdu: 'اولاک رکشہ / بولان',
    service_type: 'rickshaw',
    vehicle_models: 'Rickshaw / Suzuki Bolan / Carry',
    base_fare: 100,
    per_km_charge: 40,
    waiting_charge_per_min: 10,
    minimum_fare: 150,
    cancellation_fee: 60,
    operating_hours: '6:00 AM – 11:00 PM',
    service_areas: 'Turbat City, Absar, Malikabad, UoT',
    is_active: true,
    icon_name: 'Truck',
    tagline: 'Ideal for Families & Luggage',
    capacity: '3-5 Persons',
  },
  {
    id: 'olak-car',
    service_name: 'OLAK Car',
    service_name_urdu: 'اولاک کار',
    service_type: 'car',
    vehicle_models: 'Corolla / Alto / Axio / Vitz',
    base_fare: 150,
    per_km_charge: 55,
    waiting_charge_per_min: 15,
    minimum_fare: 250,
    cancellation_fee: 100,
    operating_hours: '24/7 (All Day & Night)',
    service_areas: 'Turbat City & Airport Transfers',
    is_active: true,
    icon_name: 'Car',
    tagline: 'AC Comfort & Safe Travel',
    capacity: '4 Passengers',
  },
  {
    id: 'olak-delivery',
    service_name: 'OLAK Delivery',
    service_name_urdu: 'اولاک ڈلیوری و پارسل',
    service_type: 'delivery',
    vehicle_models: 'Motorcycle / Rickshaw Courier',
    base_fare: 100,
    per_km_charge: 25,
    waiting_charge_per_min: 10,
    minimum_fare: 150,
    cancellation_fee: 50,
    operating_hours: '8:00 AM – 9:00 PM',
    service_areas: 'Turbat City Limits (Up to 15 KG)',
    is_active: true,
    icon_name: 'Package',
    tagline: 'Instant Door-to-Door Delivery',
    capacity: 'Documents, Food & Parcels',
  },
];

export const INITIAL_INTERCITY_ROUTES: IntercityRoute[] = [
  {
    id: 'route-turbat-gwadar',
    origin_city: 'Turbat',
    destination_city: 'Gwadar',
    estimated_distance_km: 170,
    estimated_duration: '2.5 Hours (M-8 Highway)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 3500,
    car_comfort_fare: 5000,
    delivery_parcel_fare: 800,
    is_active: true,
  },
  {
    id: 'route-turbat-pasni',
    origin_city: 'Turbat',
    destination_city: 'Pasni',
    estimated_distance_km: 135,
    estimated_duration: '2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 3000,
    car_comfort_fare: 4200,
    delivery_parcel_fare: 700,
    is_active: true,
  },
  {
    id: 'route-turbat-jiwani',
    origin_city: 'Turbat',
    destination_city: 'Jiwani',
    estimated_distance_km: 210,
    estimated_duration: '3.5 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 4500,
    car_comfort_fare: 6000,
    delivery_parcel_fare: 1000,
    is_active: true,
  },
  {
    id: 'route-turbat-panjgur',
    origin_city: 'Turbat',
    destination_city: 'Panjgur',
    estimated_distance_km: 220,
    estimated_duration: '3.5 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 4500,
    car_comfort_fare: 6200,
    delivery_parcel_fare: 1000,
    is_active: true,
  },
  {
    id: 'route-turbat-tump',
    origin_city: 'Turbat',
    destination_city: 'Tump',
    estimated_distance_km: 70,
    estimated_duration: '1.2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 1800,
    car_comfort_fare: 2600,
    delivery_parcel_fare: 500,
    is_active: true,
  },
  {
    id: 'route-turbat-mand',
    origin_city: 'Turbat',
    destination_city: 'Mand',
    estimated_distance_km: 115,
    estimated_duration: '2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 2500,
    car_comfort_fare: 3500,
    delivery_parcel_fare: 650,
    is_active: true,
  },
  {
    id: 'route-turbat-karachi',
    origin_city: 'Turbat',
    destination_city: 'Karachi',
    estimated_distance_km: 780,
    estimated_duration: '11-12 Hours (Coastal Highway)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 16000,
    car_comfort_fare: 22000,
    delivery_parcel_fare: 2500,
    is_active: true,
  },
  {
    id: 'route-turbat-quetta',
    origin_city: 'Turbat',
    destination_city: 'Quetta',
    estimated_distance_km: 760,
    estimated_duration: '12 Hours (via Hoshab/Surab)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 17000,
    car_comfort_fare: 23000,
    delivery_parcel_fare: 2500,
    is_active: true,
  },
];

export const INITIAL_PROMOTIONS: PromotionBanner[] = [
  {
    id: 'promo-1',
    title: 'Turbat Summer Ride Bonanza',
    subtitle: 'Get 20% flat discount on all car & bike rides across Turbat city zones.',
    image_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#fares',
    badge: '20% OFF',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'promo-2',
    title: 'University of Turbat Student Shuttle',
    subtitle: 'Affordable daily commute for UoT students & faculty with instant door-to-campus booking.',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#fares',
    badge: 'Student Deal',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'promo-3',
    title: 'Express Highway: Turbat to Gwadar Port',
    subtitle: 'Direct AC luxury cars and parcel delivery to Gwadar starting at just PKR 3,500.',
    image_url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#intercity',
    badge: 'Highway Express',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: 'olak_settings',
  company_name: 'OLAK (اولاک)',
  company_name_urdu: 'اولاک موبلٹی و ڈلیوری سروس',
  tagline: 'Safar Har Qadam Asan (سفر ہر قدم آسان)',
  tagline_urdu: 'آسان سفر، آسان کمائی — آپ کی سواری، آپ کا اعتماد',
  phone: '+92 3350455599',
  whatsapp: '+92 3340468649',
  email: 'olak.tbt@gmail.com',
  address: 'Office Near City Thana, Thana Road, Turbat, Balochistan',
  address_urdu: 'دفتر نزد سٹی تھانہ، تھانہ روڈ، تربت، بلوچستان',
  operating_cities: [
    'Turbat', 'Gwadar', 'Pasni', 'Jiwani', 'Tump', 'Mand', 
    'Panjgur', 'Quetta', 'Hub Chowki', 'Karachi', 'Khuzdar', 'Awaran'
  ],
  commission_percentage: 10.0,
  is_booking_active: true,
  admin_pin: 'admin123',
};
