import { PricingRate, IntercityRoute, SiteSettings, PromotionBanner, CityLandmark, DriverPromoCard } from './types';

export const TURBAT_LANDMARKS: CityLandmark[] = [
  // Major Hubs & Emergency
  { id: 'lm-1', name: 'City Thana (Police Station), Thana Road', shortName: 'City Thana', nameUrdu: 'سٹی تھانہ، تھانہ روڈ', name_urdu: 'سٹی تھانہ، تھانہ روڈ', area: 'Central Turbat', category: 'govt', lat: 26.0031, lng: 63.0544, is_active: true },
  { id: 'lm-2', name: 'Turbat International Airport', shortName: 'Airport', nameUrdu: 'تربت انٹرنیشنل ایئرپورٹ', name_urdu: 'تربت انٹرنیشنل ایئرپورٹ', area: 'Airport Road', category: 'airport', lat: 25.9863, lng: 63.0312, is_active: true },
  { id: 'lm-3', name: 'University of Turbat (UoT) Campus', shortName: 'UoT Campus', nameUrdu: 'یونیورسٹی آف تربت', name_urdu: 'یونیورسٹی آف تربت', area: 'M-8 Ginna', category: 'education', lat: 26.0289, lng: 63.0978, is_active: true },
  { id: 'lm-4', name: 'Main Bazaar / Shahi Bazaar', shortName: 'Shahi Bazaar', nameUrdu: 'مین بازار / شاہی بازار', name_urdu: 'مین بازار / شاہی بازار', area: 'Central Turbat', category: 'shopping', lat: 26.0055, lng: 63.0501, is_active: true },
  { id: 'lm-5', name: 'District Headquarters (DHQ) Hospital Turbat', shortName: 'DHQ Hospital', nameUrdu: 'ڈی ایچ کیو ہسپتال تربت', name_urdu: 'ڈی ایچ کیو ہسپتال تربت', area: 'Hospital Road', category: 'hospital', lat: 26.0082, lng: 63.0485, is_active: true },
  { id: 'lm-19', name: 'Red Crescent (Hilal-e-Ahmar) Hospital', shortName: 'Red Crescent', nameUrdu: 'ہلال احمر ہسپتال', name_urdu: 'ہلال احمر ہسپتال', area: 'Absar Road', category: 'hospital', lat: 25.9950, lng: 63.0705, is_active: true },
  
  // Bazaars, Markets & Commercial
  { id: 'lm-18', name: 'Sabzi Mandi (Fruit & Veg Market)', shortName: 'Sabzi Mandi', nameUrdu: 'سبزی منڈی تربت', name_urdu: 'سبزی منڈی تربت', area: 'Market Road', category: 'shopping', lat: 26.0070, lng: 63.0468, is_active: true },
  { id: 'lm-28', name: 'Cloth & Garments Market, Shahi Bazaar', shortName: 'Cloth Market', nameUrdu: 'کپڑا مارکیٹ تربت', name_urdu: 'کپڑا مارکیٹ تربت', area: 'Shahi Bazaar', category: 'shopping', lat: 26.0050, lng: 63.0495, is_active: true },
  { id: 'lm-29', name: 'Mobile & Electronics Plaza', shortName: 'Mobile Market', nameUrdu: 'موبائل مارکیٹ', name_urdu: 'موبائل مارکیٹ', area: 'Commercial Road', category: 'shopping', lat: 26.0040, lng: 63.0510, is_active: true },
  { id: 'lm-15', name: 'Meezan Bank Chowk', shortName: 'Meezan Bank', nameUrdu: 'میزان بینک چوک', name_urdu: 'میزان بینک چوک', area: 'Commercial Center', category: 'bank', lat: 26.0044, lng: 63.0522, is_active: true },
  { id: 'lm-16', name: 'National Bank (NBP) Main Branch', shortName: 'NBP Cinema Rd', nameUrdu: 'نیشنل بینک مین برانچ', name_urdu: 'نیشنل بینک مین برانچ', area: 'Cinema Road', category: 'bank', lat: 26.0062, lng: 63.0515, is_active: true },
  { id: 'lm-37', name: 'Habib Bank (HBL) City Branch', shortName: 'HBL City Branch', nameUrdu: 'حبیب بینک سٹی برانچ', name_urdu: 'حبیب بینک سٹی برانچ', area: 'Shahi Bazaar', category: 'bank', lat: 26.0051, lng: 63.0508, is_active: true },
  { id: 'lm-38', name: 'Al-Falah Super Store & Market', shortName: 'Al-Falah Store', nameUrdu: 'الفلاح سپر اسٹور', name_urdu: 'الفلاح سپر اسٹور', area: 'Commercial Center', category: 'shopping', lat: 26.0060, lng: 63.0525, is_active: true },

  // Transport & Addas
  { id: 'lm-17', name: 'Turbat Central Bus Terminal / Adda', shortName: 'Bus Terminal', nameUrdu: 'تربت جنرل بس اڈا', name_urdu: 'تربت جنرل بس اڈا', area: 'Gwadar Road', category: 'transit', lat: 25.9912, lng: 63.0450, is_active: true },
  { id: 'lm-39', name: 'Karachi & Quetta Coach Adda, Cinema Road', shortName: 'Coach Adda', nameUrdu: 'کوچ اڈا تربت', name_urdu: 'کوچ اڈا تربت', area: 'Cinema Road', category: 'transit', lat: 26.0068, lng: 63.0528, is_active: true },
  { id: 'lm-33', name: 'Nasirabad Bus Stop', shortName: 'Nasirabad Stop', nameUrdu: 'ناصرآباد بس اسٹاپ', name_urdu: 'ناصرآباد بس اسٹاپ', area: 'Kech Valley', category: 'transit', lat: 26.0310, lng: 63.0210, is_active: true },
  { id: 'lm-34', name: 'Tump Road Gateway', shortName: 'Tump Gateway', nameUrdu: 'تمپ روڈ گیٹ وے', name_urdu: 'تمپ روڈ گیٹ وے', area: 'Turbat West', category: 'transit', lat: 26.0075, lng: 63.0220, is_active: true },
  { id: 'lm-10', name: 'Ginna Road / M-8 CPEC Junction', shortName: 'M-8 Junction', nameUrdu: 'گنہ روڈ / ایم 8 جنکشن', name_urdu: 'گنہ روڈ / ایم 8 جنکشن', area: 'Ginna', category: 'transit', lat: 26.0351, lng: 63.1120, is_active: true },

  // Colleges & Schools
  { id: 'lm-14', name: 'Government Degree College for Boys', shortName: 'Degree College', nameUrdu: 'گورنمنٹ ڈگری کالج تربت', name_urdu: 'گورنمنٹ ڈگری کالج تربت', area: 'College Road', category: 'education', lat: 26.0012, lng: 63.0531, is_active: true },
  { id: 'lm-24', name: 'Balochistan Residential College (BRC)', shortName: 'BRC College', nameUrdu: 'بی آر سی کالج تربت', name_urdu: 'بی آر سی کالج تربت', area: 'Airport Highway', category: 'education', lat: 25.9790, lng: 63.0250, is_active: true },
  { id: 'lm-12', name: 'Turbat Public School & College', shortName: 'Public School', nameUrdu: 'تربت پبلک اسکول و کالج', name_urdu: 'تربت پبلک اسکول و کالج', area: 'Absar Road', category: 'education', lat: 25.9981, lng: 63.0699, is_active: true },
  { id: 'lm-40', name: 'Government Girls Degree College', shortName: 'Girls College', nameUrdu: 'گورنمنٹ گرلز ڈگری کالج', name_urdu: 'گورنمنٹ گرلز ڈگری کالج', area: 'Absar Road', category: 'education', lat: 25.9965, lng: 63.0682, is_active: true },
  { id: 'lm-41', name: 'Law College Complex Turbat', shortName: 'Law College', nameUrdu: 'لاء کالج تربت', name_urdu: 'لاء کالج تربت', area: 'Court Road', category: 'education', lat: 26.0028, lng: 63.0570, is_active: true },

  // Government & Legal Complex
  { id: 'lm-22', name: 'Deputy Commissioner (DC) Office Complex', shortName: 'DC Office', nameUrdu: 'ڈی سی آفس کمپلیکس', name_urdu: 'ڈی سی آفس کمپلیکس', area: 'DC Office Road', category: 'govt', lat: 26.0090, lng: 63.0575, is_active: true },
  { id: 'lm-21', name: 'Session Courts Complex Turbat', shortName: 'Session Courts', nameUrdu: 'سیشن کورٹ تربت', name_urdu: 'سیشن کورٹ تربت', area: 'Court Road', category: 'govt', lat: 26.0020, lng: 63.0560, is_active: true },
  { id: 'lm-11', name: 'Circuit House Turbat', shortName: 'Circuit House', nameUrdu: 'سرکٹ ہاؤس تربت', name_urdu: 'سرکٹ ہاؤس تربت', area: 'Officers Colony', category: 'govt', lat: 26.0101, lng: 63.0588, is_active: true },
  { id: 'lm-20', name: 'Model Town Police Station', shortName: 'Model Town Thana', nameUrdu: 'ماڈل ٹاؤن تھانہ', name_urdu: 'ماڈل ٹاؤن تھانہ', area: 'Model Town', category: 'govt', lat: 26.0142, lng: 63.0610, is_active: true },
  { id: 'lm-23', name: 'Turbat Press Club', shortName: 'Press Club', nameUrdu: 'تربت پریس کلب', name_urdu: 'تربت پریس کلب', area: 'Officers Colony', category: 'govt', lat: 26.0088, lng: 63.0595, is_active: true },
  { id: 'lm-42', name: 'NADRA Mega Center, Airport Road', shortName: 'NADRA Center', nameUrdu: 'نادرا میگا سینٹر تربت', name_urdu: 'نادرا میگا سینٹر تربت', area: 'Airport Road', category: 'govt', lat: 25.9930, lng: 63.0410, is_active: true },

  // Neighborhoods, Chowks & Points
  { id: 'lm-6', name: 'Absar Chowk', shortName: 'Absar Chowk', nameUrdu: 'ابسر چوک', name_urdu: 'ابسر چوک', area: 'Absar', category: 'area', lat: 25.9924, lng: 63.0721, is_active: true },
  { id: 'lm-7', name: 'Malikabad / Aabsar Road', shortName: 'Malikabad', nameUrdu: 'ملک آباد / ابسر روڈ', name_urdu: 'ملک آباد / ابسر روڈ', area: 'Malikabad', category: 'area', lat: 26.0125, lng: 63.0655, is_active: true },
  { id: 'lm-8', name: 'D-Baloch Chowk', shortName: 'D-Baloch', nameUrdu: 'ڈی بلوچ چوک', name_urdu: 'ڈی بلوچ چوک', area: 'D-Baloch', category: 'area', lat: 26.0188, lng: 63.0412, is_active: true },
  { id: 'lm-9', name: 'Singanisar Chowk', shortName: 'Singanisar', nameUrdu: 'سنگانی سر چوک', name_urdu: 'سنگانی سر چوک', area: 'Singanisar', category: 'area', lat: 25.9875, lng: 63.0611, is_active: true },
  { id: 'lm-25', name: 'Koshkalat Chowk', shortName: 'Koshkalat', nameUrdu: 'کوشکلات چوک', name_urdu: 'کوشکلات چوک', area: 'Koshkalat', category: 'area', lat: 26.0220, lng: 63.0480, is_active: true },
  { id: 'lm-26', name: 'Koh-e-Murad Ziyarat Point', shortName: 'Koh-e-Murad', nameUrdu: 'کوہ مراد زیارت', name_urdu: 'کوہ مراد زیارت', area: 'Koh-e-Murad', category: 'area', lat: 26.0245, lng: 63.0680, is_active: true },
  { id: 'lm-27', name: 'Aabsar Purana (Old Absar)', shortName: 'Purana Absar', nameUrdu: 'پرانا ابسر', name_urdu: 'پرانا ابسر', area: 'Absar South', category: 'area', lat: 25.9890, lng: 63.0760, is_active: true },
  { id: 'lm-31', name: 'Shahrak Chowk', shortName: 'Shahrak', nameUrdu: 'شاہرک چوک', name_urdu: 'شاہرک چوک', area: 'East Turbat CPEC', category: 'area', lat: 26.0410, lng: 63.1350, is_active: true },
  { id: 'lm-32', name: 'Nodez Area', shortName: 'Nodez', nameUrdu: 'نودز علاقہ', name_urdu: 'نودز علاقہ', area: 'North Turbat', category: 'area', lat: 26.0260, lng: 63.0350, is_active: true },
  { id: 'lm-35', name: 'City Family Park & Recreation', shortName: 'City Park', nameUrdu: 'سٹی فیملی پارک', name_urdu: 'سٹی فیملی پارک', area: 'Commissioner Road', category: 'park', lat: 26.0115, lng: 63.0565, is_active: true },
  { id: 'lm-13', name: 'Kech River View Point & Bridge', shortName: 'Kech River', nameUrdu: 'کیچ ریور ویو پوائنٹ', name_urdu: 'کیچ ریور ویو پوائنٹ', area: 'Kech River', category: 'park', lat: 26.0150, lng: 63.0380, is_active: true },
  { id: 'lm-30', name: 'Mirani Dam Road Junction', shortName: 'Mirani Junction', nameUrdu: 'میرانی ڈیم روڈ موڑ', name_urdu: 'میرانی ڈیم روڈ موڑ', area: 'West Turbat', category: 'area', lat: 26.0110, lng: 63.0290, is_active: true },
  { id: 'lm-36', name: 'Turbat Base 44 / Road Base', shortName: 'Base 44', nameUrdu: 'تربت روڈ بیس 44', name_urdu: 'تربت روڈ بیس 44', area: 'Turbat Base Road', category: 'area', lat: 25.9975, lng: 63.0390, is_active: true },
];

export const INITIAL_LANDMARKS = TURBAT_LANDMARKS;

export const INITIAL_PRICING_RATES: PricingRate[] = [
  {
    id: 'olak-bike',
    service_name: 'OLAK Bike',
    service_name_urdu: 'اولاک بائیک',
    service_type: 'bike',
    vehicle_models: 'Motorcycle (70cc / 125cc)',
    base_fare: 50,
    per_km_charge: 25,
    waiting_charge_per_min: 5,
    minimum_fare: 80,
    cancellation_fee: 50,
    operating_hours: '6:00 AM – 12:00 AM',
    service_areas: 'Turbat City Limits & Suburbs',
    is_active: true,
    icon_name: 'Bike',
    tagline: 'Fastest & Most Affordable',
    capacity: '1 Rider',
  },
  {
    id: 'olak-rickshaw',
    service_name: 'OLAK Rickshaw / Bolan',
    service_name_urdu: 'اولاک رکشہ / بولان',
    service_type: 'rickshaw',
    vehicle_models: 'Rickshaw / Suzuki Bolan / Carry',
    base_fare: 100,
    per_km_charge: 40,
    waiting_charge_per_min: 10,
    minimum_fare: 150,
    cancellation_fee: 60,
    operating_hours: '6:00 AM – 11:00 PM',
    service_areas: 'Turbat City, Absar, Malikabad, UoT',
    is_active: true,
    icon_name: 'Truck',
    tagline: 'Ideal for Families & Luggage',
    capacity: '3-5 Persons',
  },
  {
    id: 'olak-car',
    service_name: 'OLAK Car',
    service_name_urdu: 'اولاک کار',
    service_type: 'car',
    vehicle_models: 'Corolla / Alto / Axio / Vitz',
    base_fare: 150,
    per_km_charge: 55,
    waiting_charge_per_min: 15,
    minimum_fare: 250,
    cancellation_fee: 100,
    operating_hours: '24/7 (All Day & Night)',
    service_areas: 'Turbat City & Airport Transfers',
    is_active: true,
    icon_name: 'Car',
    tagline: 'AC Comfort & Safe Travel',
    capacity: '4 Passengers',
  },
  {
    id: 'olak-delivery',
    service_name: 'OLAK Delivery',
    service_name_urdu: 'اولاک ڈلیوری و پارسل',
    service_type: 'delivery',
    vehicle_models: 'Motorcycle / Rickshaw Courier',
    base_fare: 100,
    per_km_charge: 25,
    waiting_charge_per_min: 10,
    minimum_fare: 150,
    cancellation_fee: 50,
    operating_hours: '8:00 AM – 9:00 PM',
    service_areas: 'Turbat City Limits (Up to 15 KG)',
    is_active: true,
    icon_name: 'Package',
    tagline: 'Instant Door-to-Door Delivery',
    capacity: 'Documents, Food & Parcels',
  },
];

export const INITIAL_INTERCITY_ROUTES: IntercityRoute[] = [
  {
    id: 'route-turbat-gwadar',
    origin_city: 'Turbat',
    destination_city: 'Gwadar',
    estimated_distance_km: 170,
    estimated_duration: '2.5 Hours (M-8 Highway)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 3500,
    car_comfort_fare: 5000,
    delivery_parcel_fare: 800,
    is_active: true,
  },
  {
    id: 'route-turbat-pasni',
    origin_city: 'Turbat',
    destination_city: 'Pasni',
    estimated_distance_km: 135,
    estimated_duration: '2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 3000,
    car_comfort_fare: 4200,
    delivery_parcel_fare: 700,
    is_active: true,
  },
  {
    id: 'route-turbat-jiwani',
    origin_city: 'Turbat',
    destination_city: 'Jiwani',
    estimated_distance_km: 210,
    estimated_duration: '3.5 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 4500,
    car_comfort_fare: 6000,
    delivery_parcel_fare: 1000,
    is_active: true,
  },
  {
    id: 'route-turbat-panjgur',
    origin_city: 'Turbat',
    destination_city: 'Panjgur',
    estimated_distance_km: 220,
    estimated_duration: '3.5 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 4500,
    car_comfort_fare: 6200,
    delivery_parcel_fare: 1000,
    is_active: true,
  },
  {
    id: 'route-turbat-tump',
    origin_city: 'Turbat',
    destination_city: 'Tump',
    estimated_distance_km: 70,
    estimated_duration: '1.2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 1800,
    car_comfort_fare: 2600,
    delivery_parcel_fare: 500,
    is_active: true,
  },
  {
    id: 'route-turbat-mand',
    origin_city: 'Turbat',
    destination_city: 'Mand',
    estimated_distance_km: 115,
    estimated_duration: '2 Hours',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 2500,
    car_comfort_fare: 3500,
    delivery_parcel_fare: 650,
    is_active: true,
  },
  {
    id: 'route-turbat-karachi',
    origin_city: 'Turbat',
    destination_city: 'Karachi',
    estimated_distance_km: 780,
    estimated_duration: '11-12 Hours (Coastal Highway)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 16000,
    car_comfort_fare: 22000,
    delivery_parcel_fare: 2500,
    is_active: true,
  },
  {
    id: 'route-turbat-quetta',
    origin_city: 'Turbat',
    destination_city: 'Quetta',
    estimated_distance_km: 760,
    estimated_duration: '12 Hours (via Hoshab/Surab)',
    pricing_model: 'fixed',
    per_km_rate: 25,
    car_economy_fare: 17000,
    car_comfort_fare: 23000,
    delivery_parcel_fare: 2500,
    is_active: true,
  },
];

export const INITIAL_PROMOTIONS: PromotionBanner[] = [
  {
    id: 'promo-1',
    title: 'Turbat Summer Ride Bonanza',
    subtitle: 'Get 20% flat discount on all car & bike rides across Turbat city zones.',
    image_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#fares',
    badge: '20% OFF',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'promo-2',
    title: 'University of Turbat Student Shuttle',
    subtitle: 'Affordable daily commute for UoT students & faculty with instant door-to-campus booking.',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#fares',
    badge: 'Student Deal',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'promo-3',
    title: 'Express Highway: Turbat to Gwadar Port',
    subtitle: 'Direct AC luxury cars and parcel delivery to Gwadar starting at just PKR 3,500.',
    image_url: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=1200&q=80',
    link_url: '/#intercity',
    badge: 'Highway Express',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: 'olak_settings',
  company_name: 'OLAK (اولاک)',
  company_name_urdu: 'اولاک موبلٹی و ڈلیوری سروس',
  tagline: 'Safar Har Qadam Asan (سفر ہر قدم آسان)',
  tagline_urdu: 'آسان سفر، آسان کمائی — آپ کی سواری، آپ کا اعتماد',
  phone: '+92 3350455599',
  whatsapp: '+92 3340468649',
  email: 'olak.tbt@gmail.com',
  address: 'Office Near City Thana, Thana Road, Turbat, Balochistan',
  address_urdu: 'دفتر نزد سٹی تھانہ، تھانہ روڈ، تربت، بلوچستان',
  operating_cities: [
    'Turbat', 'Gwadar', 'Pasni', 'Jiwani', 'Tump', 'Mand', 
    'Panjgur', 'Quetta', 'Hub Chowki', 'Karachi', 'Khuzdar', 'Awaran'
  ],
  commission_percentage: 10.0,
  is_booking_active: true,
  admin_pin: 'admin@olak1234@#&678',
};

export const INITIAL_DRIVER_PROMOS: DriverPromoCard[] = [
  {
    id: 'driver-promo-bike',
    category_badge: 'Motorcycle 70cc / 125cc',
    title: 'Register Your Bike Captain Account',
    title_urdu: 'اپنی بائیک رجسٹر کروائیں — آزادی سے کمائیں',
    image_url: '/assets/bike-poster.jpg',
    bullets: [
      'Daily Cash Earnings on Every Trip',
      'Only 10% Platform Fee — Keep 90%',
      'Flexible Hours — Work When You Want'
    ],
    cta_text: 'Register Bike Captain',
    cta_link: '/captain/',
    is_active: true,
  },
  {
    id: 'driver-promo-car',
    category_badge: 'Car / Bolan / Rickshaw',
    title: 'Register Commercial Car, Bolan or Rickshaw',
    title_urdu: 'آسان سفر، آسان کمائی — آپ کا اعتماد',
    image_url: '/assets/car-poster.jpg',
    bullets: [
      'City Rides, Airport Pickups & Intercity Trips',
      'Respectful & Dignified Family Commuters',
      'Quick Online Verification in 24 Hours'
    ],
    cta_text: 'Register Car / Rickshaw',
    cta_link: '/captain/',
    is_active: true,
  },
];
